### ISSUE TITLE
Extracting contact count from segmentation

### ISSUE THREAD

**Issue by kmellanson** [biocompibens/cellmodelling#1]
Hi,

I'm trying to use your software to extract the cell parameters and cell contact counts, but shuffling my data on the hardware that I have available turns out to be prohibitively slow.

Is there any way to circumvent the shuffling and still get the cell contact count?

**Comment by L-EL** [comment]
Hi,

it is not possible to shunt the simulation with the current code, but before the iterative steps, it creates a file with all the cell parameters in the output directory, that you can use. 
The cell contact count is not a parameter used and extracted by SET, you will not find it in the cell parameters. We obtained this measurement with a post-processing analysis. You can find the relative codes in the analysis directory.
